name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.10'  

    - name: Install dependencies
      run: make

    - name: Run build
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sly-python-package-${{ github.job  }}
        path: dist/
